config/routes.rb
CsvDemo::Application.routes.draw do

  resources :employees do
  	collection do 
  		post "importCsv"
  		post "get_child"
  	end
  end	
  devise_for :users
  
  resources :users, :only => [:show, :index]

  
	root :to => "employees#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :position, :position_title, :report_to
  
  #validates :reportto, :uniqueness => true
  #validates :last_name, :presence => true
  #validates :first_name, :presence => true
	before_save :default_first_name, :default_last_name, :default_position_title 

  def self.build_from_csv(row)
  	#raise row[1].inspect 
  	@error = nil  	
  	#if row[1] == '6'
  	#	@error = 'Maisa Pride'  		
  	#end 	
	
  	cust = Employee.find_or_initialize_by_position(row[0])  	
    cust.attributes ={:position => row[0],
     :report_to => row[1],
     :first_name => row[2],
     :last_name => row[3],
     :position_title => row[4]}
    return cust,@error
  end
  
  def self.EmployeeHeader  	
  	"Position,ReportTo,First Name,Last Name,Position title".split(',')
  end
  
  protected
  
  def default_first_name
    self.first_name ||= 'Vacant'
  end
  
  def default_last_name
    self.last_name ||= 'Position'
  end
  
  def default_position_title
  	self.position_title ||= 'Position title'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	## VALIDATIONS
	validates_presence_of :name
	validates_uniqueness_of :name, :email, :case_sensitive => false
	
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  protected
  
  def self.find_for_database_authentication(conditions = {})
  	self.where("name = ? ", conditions[:name]).limit(1).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout "employee"	
end

app/controllers/employees_controller.rb
require 'csv'
class EmployeesController < ApplicationController
	
	layout "application"
	
	before_filter :authenticate_user!
  # GET /employees
  # GET /employees.json
  def index    
    @employees = Employee.all
    #raise @employees.inspect
    @root_node = Employee.all.first
		#Employee.report(@employees)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
  
  def importCsv
  	if request.post? && params[:file].present?
  		infile = params[:file].read 		  		
      n, errs = 0, []
			parentRows = 0
      CSV.parse(infile) do |row|
        n += 1               
        next if n == 1 or row.join.blank? # SKIP: header i.e. first row OR blank row
        @importproduct, @custError = Employee.build_from_csv(row) # build_from_csv method will map customer attributes & build new customer record         
        if @importproduct.valid? # Save upon valid otherwise collect error records to export         
          @importproduct.save          
        else        	     	
        	row.push @importproduct.errors.full_messages.join(',')
        	row.push @custError if !@custError.blank?
          errs << row
        end
      end
      
      if errs.any?      	
        errFile ="errors_#{Date.today.strftime('%d%b%y')}.csv"
        errs.insert(0, Employee.importHeader)
        errCSV = CSV.generate do |csv|
          errs.each {|row| csv << row}
        end
        
        send_data errCSV, :type => 'text/csv; charset=iso-8859-1; header=present',:disposition => "attachment; filename=#{errFile}.csv"
        if @importproduct.errors == true
        	redirect_to employees_path, :notice=>"Errors: #{@importproduct.errors}" and return
        end
      else
        redirect_to employees_path, :notice=>'Import successful'
      end
    end
  end
  
  def get_child
  	@childs	= Employee.where(:report_to => params[:position]) 
  	render :layout => false 	
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
  def index
  	@users = User.all
  end

  def show
  	@uses = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def display_categories(categories)
   	ret = "<ul>"
    for category in categories
      if category.report_to == 0
	      ret += "<li class='collapsed'>"
	      ret += "<input type='checkbox'>"
	      ret += category.first_name
	      ret += " "
	      ret += category.last_name 
	      ret += "("
	      ret += category.position_title 
	      ret += ")"
	      ret += find_all_subcategories(category)
	      ret += "</li>"
      end
    end
    ret += "</ul>"
    return ret.html_safe
  end
  
  def find_all_subcategories(category)
    @childs = Employee.where(:report_to => category.position)
    if @childs.size > 0
      ret = '<ul>'
      @childs.each { |subcat|       
        @childs1 = Employee.where(:report_to => subcat.position)
        if @childs1.size > 0
          ret += "<li class='collapsed'>"
          ret += "<input type='checkbox'>"
          ret += subcat.first_name
          ret += " "
          ret += subcat.last_name 
	        ret += "("
	        ret += subcat.position_title
          ret += ")"
          ret += find_all_subcategories(subcat)
          ret += '</li>'
        else
          ret += "<li class='collapsed'>"          
          ret += "<input type='checkbox'>"
          ret += subcat.first_name
          ret += " "
          ret += subcat.last_name
          ret += "(" 
	        ret += subcat.position_title 
          ret += ")"
          ret += '</li>'
        end
        }
      ret += '</ul>'
    end
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employees/_form.html.erb
<%= form_for(@import) do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :report_to %><br />
    <%= f.number_field :reportto %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :position_title %><br />
    <%= f.text_area :positiontitle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing import</h1>

<%= render 'form' %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/employees/get_child.html.erb
<% @childs.each do |child| %>	
	<ul>
		<li class="collapsed"><input type="checkbox"><span><b><%= link_to child.first_name, "#", :class => "tree", :id => "#{child.position}" %> <%= child.last_name %>&nbsp;(<%= child.position_title %>)</b></span>
		<div id="childs1"></div>
	</ul>
<% end %>


<script type="text/javascript">
    $(document).ready(function(){
    	$(".tree").click(function(event){      
      	var targetId = event.target.id;								
				$.ajax({
							type: "POST",
              url: '/employees/get_child',
              data: { position: targetId},              
              cache: false,
              beforeSend: function( ) {
                $('#loading').append("loading...");
              },
              success: function(html){
                $('#loading').empty();
                $('#childs1').append(html); 
               },
              error: function( ) {
                $('#loading').append("...error loading...");
              }
            });
    	});    		
    });
</script>

app/views/employees/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
<%= javascript_include_tag('jquery.tree','jquery.treecheckbox','jquery.treecollapse','jquery.treeselect','jquery.treeview')%>
<%= stylesheet_link_tag('jquery.tree','jquery-ui','jquery.treeview.css')%>
<script type="text/javascript">
  $(document).ready(function() {
      $( "#accordion" ).accordion({
          'collapsible': true,
          'active': -1
      });
      $('.jquery').each(function() {
          eval($(this).html());
      });
      $('.button').button();
  });
</script>
</head>
<body>
<h1>Listing imports</h1>
	<%= form_tag importCsv_employees_path, :method => 'post', :multipart => true do %>
		<p>
			Select File: 
			<%= file_field_tag 'file' %>
			<%= submit_tag 'Upload data', :name => nil %>
		</p>
	<% end %>  
  <div id="example-3">
	<script class="jquery" lang="text/javascript">
      $('#example-3 div').tree({
          components: ['checkbox', 'collapse'],
          onCheck: {
              node: 'expand'
          },
          onUncheck: {
              node: 'collapse'
          }
      });
  </script>
  
	<div id="example-3 div">
    <%= display_categories(@employees) %>
  </div>
	
</body>
</html>

app/views/employees/new.html.erb
<h1>New import</h1>

<%= render 'form' %>

<%= link_to 'Back', imports_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @import.position %>
</p>

<p>
  <b>Report_to:</b>
  <%= @import.reportto %>
</p>

<p>
  <b>First_name:</b>
  <%= @import.firstname %>
</p>

<p>
  <b>Last_name:</b>
  <%= @import.lastname %>
</p>

<p>
  <b>Position_title:</b>
  <%= @import.positiontitle %>
</p>


<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
	<p>User: <%= link_to user.name %> </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Csv Tree" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %> 
		<%= javascript_include_tag "application" %>
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
<body>
	<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Csv Tree</a>
          <div class="container nav-collapse">
            <ul class="nav">
            	<%= render 'shared/navigation' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>	
	<%- flash.each do |name, msg| -%>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	<%- end -%>
	<%= yield %>

</body>
</html>

app/views/layouts/employee.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Csv Tree" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %> 
    <%= csrf_meta_tags %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Csv Tree</a>
          <div class="container nav-collapse">
            <ul class="nav">
            	<%= render 'shared/navigation' %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
           		<%- flash.each do |name, msg| -%>
								<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
							<%- end -%>   
              <%= yield %>
            </div>
            <!--
            <div class="span3">
              <div class="well sidebar-nav">
                
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div>
            </div>
            -->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Ken Peter 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
	 <li>
	 	<%= link_to('logout', destroy_user_session_path, :method => 'delete') %>
	 </li>
<% else %>
	<li>
	 	<% link_to('Login', new_user_session_path) %>
	</li>
<% end %>
<% if user_signed_in? %>
	 <li>
	 	<% link_to('Edit Account', edit_user_registration_path) %>
	</li>
<% else %>
	<li>
	 	<% link_to('Sign up', new_user_registration_path) %>
	</li>
<% end %>

app/views/users/index.html.erb
<ul class='users'>
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user %>signed up <%= user.created_at.to_date %>
		</li>
	<% end %>
<ul>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>